apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  {{- template "chart.labels" . }}
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx

