apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: sqlserver
spec:
  ports:
  - nodePort: 31090
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqlserver
  type: LoadBalancer
